spring.application.name=kalatailering

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-xxxxx.render.com:5432/kalatailering_db
spring.datasource.username=kalatailering_user
spring.datasource.password=abcd1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialectalect
